### ISSUE TITLE
Placeholder issues in Opera

### ISSUE THREAD

**Issue by Gavrisimo** [nathansmith/formalize#31]
Hello,

after implementing this script everything works except placeholder text color in Opera 11.50(build 1074).

I was using this gist to enable placeholder functionality across browsers:

https://gist.github.com/823300

If i load only that script placeholders work great everywhere.

If i load only fomalize.js everything works except placeholders in opera.

When i try to load both of these scripts, formalize stops working, but placeholders work ok everywhere.

It sure would be amazing if formalize could implement this script so we also get working placeholders across all modern browsers.

**Comment by nathansmith** [comment]
Since placeholder itself works in Opera, there's not really a way to feature-detect just color styling support.

http://davidwalsh.name/html5-placeholder-css

I'm not going to add this, because the Opera team is aware of this shortcoming, and plans on adding support for it eventually...

http://dev.opera.com/forums/topic/841252?t=1296553904&page=1#comment8072202

What I did with Formalize, was style the '-moz' and '-webkit' placeholders to match Opera, for consistency.
