### ISSUE TITLE
wrong number of arguments (3 for 1) for `image-url'

### ISSUE THREAD

**Issue by cosenmarco** [nathansmith/formalize#39]
In sass + compass version of formalize I get this error when importing:

```
wrong number of arguments (3 for 1) for `image-url'
```

I solved quickly and dirtly by replacing

```
image-url("button.png", false, false)
```

 with

```
image-url("button.png")
```

and doing similarily for all other three arguments occourences.

**Comment by nathansmith** [comment]
Weird, I was under the impression that was the way to do it (and it seems to work for me).

Here's the documentation for it...

http://compass-style.org/reference/compass/helpers/urls/#image-url

Nevertheless, I think I'm going to just change that back to be a vanilla URL:

```
url(../images/button.png)
```

That seems to be more foolproof, because (depending on if you're in a Rails project and (not) using asset pipeline, that may not work as intended anyway.

**Comment by nathansmith** [comment]
Update: After talking with @samsoffes - He just told me to rip out the `, false, false` — So I did. :)

https://github.com/nathansmith/formalize/commit/af4ba00f487a9f8775b5768cc5be9d744ec7149f
