### ISSUE TITLE
Browsers !WebKit need height: 1.8em; for select[size="0"] and select[size="1"]

### ISSUE THREAD

**Issue by isellsoap** [nathansmith/formalize#42]
`height: 1.8em;` is assigned to `select[size="0"]` and `select[size="1"]` only through the WebKit media query `@media (-webkit-min-device-pixel-ratio: 0) { … }`. At least Firefox 9 and Opera 11.6 need that declaration too, otherwise the rendered `select` is too small.

**Comment by nathansmith** [comment]
Actually, that's the point. Except for WebKit (Chrome & Safari), all browsers treat these the same...

`select`

`select[size="0"]`

`select[size="1"]`

So, I'm setting `height:auto` for `select[size]` and then _back_ to the initial single `<select>` height for WebKit.

---

Meaning, this is the desired visual result:

http://cl.ly/1b1m3R2K28333u1R3K1R

---

Note: I added that fix, after this issue was reported, related to the Drupal forms API...

https://github.com/nathansmith/formalize/issues/40

**Comment by isellsoap** [comment]
I don’t get it. As it is now adding a `select="0"` or `select="1"` [here](https://github.com/nathansmith/formalize/blob/master/jquery_demo.html#L57) renders a smaller `select` than the `input` next to it in Firefox and Opera. Is that intended?

---

Reading your edit now. I think we talked at cross purposes. ^_^

**Comment by nathansmith** [comment]
I'm not sure what you mean. This is what I see...

http://cl.ly/1A111f2D1L0N0L0C1R1f

Can you post a screenshot of what you're seeing?

**Comment by isellsoap** [comment]
Strangely enough I can’t reproduce the issue in Firefox anymore.
Sorry for the false alarm. But it exists in [Opera](http://img267.imageshack.us/img267/9017/ohnetitelc.png) and in [IE 9](http://img51.imageshack.us/img51/5746/bildschirmfoto20120112u.png).

**Comment by nathansmith** [comment]
Okay, this should fix it...

https://github.com/nathansmith/formalize/commit/b7cb005b46d671f93b6d7c086eedb0527a2bac28

Thanks for the back and forth on Twitter, helping me to understand the issue.
