### ISSUE TITLE
input:focus styling not applied when focusing on invalid elements

### ISSUE THREAD

**Issue by kdonald** [nathansmith/formalize#46]
I have a form that has several "required" fields (the HTML5 attribute 'required' present). When focusing on one of these fields to enter a value, the field is not highlighted like you would expect. This appears to be because the following "input:invalid" styles are resetting the input:focus box shadow:

input:invalid,
button:invalid,
select:invalid,
textarea:invalid {
  -webkit-box-shadow: none;
  -moz-box-shadow: none;
  -o-box-shadow: none;
  box-shadow: none;
}

Removing the above styles gives me a focus highlight behavior I expect. I'm not sure if the current behavior is intentional... I found it a little odd so I thought I would report it.

**Comment by nathansmith** [comment]
Ah, I had done this to prevent Firefox (and other browsers) from looking "invalid" while typing.

For instance, if it was `type="email"` then typing `john.doe` would be technically invalid until finishing it out with `john.doe@example.com` so Firefox would add a red glow as you'd type — A disconcerting user experience.

I'm thinking, maybe move this rule further up in the code, so that `:focus` and `:active` can still take effect?

**Comment by kdonald** [comment]
I'm having trouble reproducing the disconcerting behavior you refer to... I only see a red glow after focus is lost with an invalid value, which is what I expect.

**Comment by kdonald** [comment]
That was in Firefox btw... just tried in Chrome & it doesn't seem to display a red glow at all. I wonder if this is an opportunity for new cross-platform support in formalize?

**Comment by nathansmith** [comment]
Ah, now I (think I) remember. So, I think that by adding an `:invalid` style, Chrome would apply it prematurely as the user would type.

**Comment by nathansmith** [comment]
@kdonald — I fixed this, and pushed...

https://github.com/nathansmith/formalize/commit/5b7e8445b7e0a6ba3263b877ebac8a1f61ea468a

And, I am still (un-)styling `:invalid` because if any styling is added, Chrome and Firefox both show inputs (that don't meet their criteria for validity) as invalid, even on page-load — Which is an odd user experience, when the user has not (yet) even begun to interact with a form.
