### ISSUE TITLE
jQuery version requirements

### ISSUE THREAD

**Issue by mvance** [nathansmith/formalize#60]
In trying to debug an [issue with the Drupal Commons project](http://drupal.org/node/1898276#comment-6999206), I found that the 1.4.4 version of jQuery that ships by default with Drupal 7 causes problems with Formalize. It appears that the issue stems from the fact that the [on() method was added in jQuery 1.7](http://api.jquery.com/on/).

Is the jQuery version requirement documented? Also, is there any chance of making Formalize backwards compatible with jQuery 1.4.4?

Thanks!

**Comment by nathansmith** [comment]
Ah, I use Formalize's styles on my own site (powered by Drupal 7) but hadn't actually made use of the JS.

I hadn't made a note of the jQuery version requirement anywhere, but you bring up a good point.

It's probably worth providing a back-compatible version, since it'd be a quick fix to do so.

I'll look into that soon.

**Comment by grasmash** [comment]
Just ran into this issue myself! Thanks!

**Comment by nathansmith** [comment]
I haven't forgotten about this. Finally taking a look at it. (Been busy with work/life lately.)

I should have a "legacy jQuery support" version ready soon.

**Comment by nathansmith** [comment]
Okay, I've added a separate "jquery.formalize.legacy.js" file that's compatible with jQuery 1.4.4…

https://github.com/nathansmith/formalize/blob/master/assets/js/jquery.formalize.legacy.js
